#!/bin/bash
clear
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[40;1;37m            SSH Account            \E[0m"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -p "Username : " Login
read -p "Password : " Pass
read -p "Max IP   : " iplimit
read -p "Expired (hari): " masaaktif
sleep 1
clear
#limitip
if [[ $iplimit -gt 0 ]]; then
echo -e "$iplimit" > /etc/funny/limit/ssh/ip/$Login
else
echo > /dev/null
fi
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
clear
echo -e "══════════════════════════"
echo -e "    <=  SSH ACCOUNT =>"
echo -e "══════════════════════════"
echo -e ""
echo -e "Username     : $Login"
echo -e "Password     : $Pass"
echo -e "CITY         : $(cat /root/.mycity)"
echo -e "ISP          : $(cat /root/.myisp)"
echo -e "Host/IP      : $(cat /etc/xray/domain)"
echo -e "NSDOMAIN     : $(cat /etc/xray/dns)"
echo -e "PUBKEY       : $(cat /etc/slowdns/server.pub)"
echo -e "Slowdns      : 53, 443"
echo -e "Udp Custom   : 1-65535"
echo -e "Port ssl/tls : 443, 2096"
echo -e "Port non tls : 2082, 80, 8080"
echo -e "BadVpn       : 7200, 7300"      
echo -e ""
echo -e "══════════════════════════"
echo -e "Payload Ws   => GET wss://bug.com/ HTTP/1.1[crlf]Host: $(cat /etc/xray/domain)[crlf]Upgrade: websocket[crlf][crlf]"
echo -e "══════════════════════════"
echo -e "     Expired => $exp"
echo -e "══════════════════════════"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
funny