#!/bin/bash
clear
echo -e "\e[32m════════════════════════════════════════" | lolcat
echo -e "             ═══[ PANEL VLESS MANAGER ]═══"
echo -e "\e[32m════════════════════════════════════════" | lolcat
echo -e ""
echo -e " [\e[36m•1\e[0m] Create Account Vless "
echo -e " [\e[36m•2\e[0m] Trial Account Vless "
echo -e " [\e[36m•3\e[0m] Extending Account Vless "
echo -e " [\e[36m•4\e[0m] Delete Account Vless "
echo -e " [\e[36m•5\e[0m] Check User Login Vless "
echo -e " [\e[36m•6\e[0m] List Member Acount Vless"
echo -e ""
echo -e " [\e[31m•0\e[0m] \e[31mBACK TO MENU\033[0m"
echo -e ""
echo -e   "Press x or [ Ctrl+C ] • To-Exit"
echo ""
echo -e "\e[32m════════════════════════════════════════" | lolcat
echo -e ""
read -p " Select menu :  "  opt
echo -e ""
case $opt in
1) clear ; add-vless ; exit ;;
2) clear ; trial-vless ; exit ;;
3) clear ; renew-vless ; exit ;;
4) clear ; del-vless ; exit ;;
5) clear ; cek-vless ; exit ;;
6) clear ; member-vless ; exit ;;
0) clear ; funny ; exit ;;
x) exit ;;
*) echo "salah tekan " ; sleep 1 ; menu-vless ;;
esac