#!/bin/bash
clear 
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[0;100;33m          • SYSTEM MENU •          \E[0m"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e " [\e[36m•1\e[0m] Change Subdomain VPN"
echo -e " [\e[36m•2\e[0m] Cek CPU/RAM/BW Monitor"
echo -e " [\e[36m•3\e[0m] Restart All Service VPN"
echo -e " [\e[36m•4\e[0m] Generate New Cert SSL"
echo -e " [\e[36m•5\e[0m] Cek Status All Service"
echo -e " [\e[36m•6\e[0m] Limit Speed Menu"
echo -e ""
echo -e " [\e[31m•0\e[0m] \e[31mBACK TO MENU\033[0m"
echo -e   ""
echo -e   "Press x or [ Ctrl+C ] • To-Exit"
echo -e   ""
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
read -p " Select menu : " opt
echo -e ""
case $opt in
1) clear ; add-host ; exit ;;
2) clear ; gotop ; exit ;;
3) clear ; restart ; exit ;;
4) clear ; certv2ray ; exit ;;
5) clear ; running ; exit ;;
6) clear ; limit-speed ; exit ;;
0) clear ; funny ; exit ;;
x) exit ;;
*) echo -e "" ; echo "Anda salah tekan" ; sleep 1 ; menu-system ;;
esac