#!/bin/bash
clear
echo -e "\e[32m════════════════════════════════════════" | lolcat
echo -e "             ═══[ PANEL SSH MANAGER ]═══"
echo -e "\e[32m════════════════════════════════════════" | lolcat
echo -e ""
echo -e " [\e[36m•1\e[0m] Create SSH & OpenVPN Account "
echo -e " [\e[36m•2\e[0m] Trial Account SSH & OpenVPN "
echo -e " [\e[36m•3\e[0m] Renew SSH & OpenVPN Account "
echo -e " [\e[36m•4\e[0m] Delete SSH & OpenVPN Account "
echo -e " [\e[36m•5\e[0m] Check User Login SSH & OpenVPN "
echo -e " [\e[36m•6\e[0m] List Member SSH & OpenVPN "
echo -e " [\e[36m•7\e[0m] Set up Autokill SSH "
echo -e " [\e[36m•8\e[0m] Cek Users Who Do Multi Login Multi"
echo -e ""
echo -e " [\e[31m•0\e[0m] \e[31mBACK TO MENU\033[0m"
echo -e ""
echo -e   "Press x or [ Ctrl+C ] • To-Exit"
echo ""
echo -e "\e[32m════════════════════════════════════════" | lolcat
echo -e ""
read -p " Select menu :  "  opt
echo -e ""
case $opt in
1) clear ; addssh ; exit ;;
2) clear ; trial ; exit ;;
3) clear ; renew ; exit ;;
4) clear ; hapus ; exit ;;
5) clear ; cekssh ; exit ;;
6) clear ; member ; exit ;;
7) clear ; autokill ; exit ;;
8) clear ; ceklim ; exit ;;
0) clear ; funny ; exit ;;
x) exit ;;
*) echo "Anda salah tekan " ; sleep 1 ; menu-ssh ;;
esac