#!/bin/bash
clear 
echo -e "\e[32m════════════════════════════════════════" | lolcat
echo -e "             ═══[ PANEL TROJAN MANAGER ]═══"
echo -e "\e[32m════════════════════════════════════════" | lolcat
echo -e ""
echo -e " [\e[36m•1\e[0m] Create Account Trojan "
echo -e " [\e[36m•2\e[0m] Trial Account Trojan "
echo -e " [\e[36m•3\e[0m] Extending Account Trojan "
echo -e " [\e[36m•4\e[0m] Delete Account Trojan "
echo -e " [\e[36m•5\e[0m] Check User Login Trojan "
echo -e " [\e[36m•6\e[0m] List Member Trojan Account "
echo -e ""
echo -e " [\e[31m•0\e[0m] \e[31mBACK TO MENU\033[0m"
echo -e   ""
echo -e   "Press x or [ Ctrl+C ] • To-Exit"
echo ""
echo -e "\e[32m════════════════════════════════════════" | lolcat
echo -e ""
read -p " Select menu : " opt
echo -e ""
case $opt in
1) clear ; add-trojan ;;
2) clear ; trial-trojan ;;
3) clear ; renew-trojan ;;
4) clear ; del-trojan ;;
5) clear ; cek-trojan ;;
6) clear ; member-trojan ;;
0) clear ; funny ;;
x) exit ;;
*) echo "SALAH TEKAN" ; sleep 1 ; menu-trojan ;;
esac