#!/bin/bash
clear
echo -e "[ \033[32mInfo\033[0m ] Restart Begin"
                sleep 1
                echo -e "[ \033[32mok\033[0m ] Restarting xray Service (via systemctl) "
                sleep 0.5
systemctl restart xray
systemctl restart badvpn1
systemctl restart badvpn3
systemctl restart badvpn2
systemctl restart haproxy
systemctl restart nginx
systemctl restart ssh
systemctl restart dropbear
systemctl restart quota
                load 
                sleep 0.5
                echo -e "[ \033[32mInfo\033[0m ] ALL Service Restarted"
                read -n 1 -s -r -p "Press any key to back on menu"

funny
